# Generated by Django 6.0.4 on 2026-04-26 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Web Application Security and Vulnerability Testing",
                        max_length=220,
                    ),
                ),
                (
                    "organizer",
                    models.CharField(
                        default="Prestige Institute of Engineering Management and Research, Indore",
                        max_length=220,
                    ),
                ),
                (
                    "event_scope",
                    models.CharField(default="National Event", max_length=80),
                ),
                (
                    "expert_name",
                    models.CharField(default="Mr. Dhavesh Srivastav", max_length=120),
                ),
                (
                    "expert_title",
                    models.CharField(
                        default="Senior Security Assurance Engineering Lead, Microsoft Bangalore, India",
                        max_length=220,
                    ),
                ),
                ("event_date", models.CharField(default="13 May 2026", max_length=80)),
                (
                    "event_time",
                    models.CharField(default="10:00 AM - 3:00 PM", max_length=80),
                ),
                (
                    "venue",
                    models.TextField(
                        default="Civil Auditorium, PIEMR, Prestige Vihar, Scheme Number 72, Vijay Nagar, Indore"
                    ),
                ),
                ("fee", models.PositiveIntegerField(default=100)),
                ("seat_limit", models.PositiveIntegerField(default=100)),
                ("registration_open", models.BooleanField(default=True)),
                ("qr_code", models.ImageField(blank=True, null=True, upload_to="qr/")),
                (
                    "upi_note",
                    models.CharField(
                        default="Scan the UPI QR code uploaded by admin", max_length=180
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Event settings",
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=140)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "participant_type",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("faculty", "Faculty"),
                            ("researcher", "Researcher"),
                            ("industry", "Industry Professional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                ("profile_data", models.JSONField(blank=True, default=dict)),
                ("transaction_id", models.CharField(blank=True, max_length=120)),
                (
                    "payment_screenshot",
                    models.FileField(blank=True, null=True, upload_to="payments/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Profile Pending"),
                            ("payment_pending", "Payment Pending"),
                            ("pending", "Awaiting Admin Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "certificate_id",
                    models.CharField(blank=True, max_length=40, null=True, unique=True),
                ),
                (
                    "certificate_pdf",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("certificate_emailed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.eventsettings",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
