# Generated by Django 6.0.4 on 2026-04-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsettings",
            name="expert_image_url",
            field=models.URLField(
                blank=True,
                default="https://media.licdn.com/dms/image/v2/D4D03AQEHp61h7Scm_Q/profile-displayphoto-scale_400_400/B4DZ1mJcS7KUAg-/0/1775535249227?e=1778716800&v=beta&t=Tw6w9QjbI7f_BpVxEfIH-vUi52lW60lmLgn2AI5FrFw",
            ),
        ),
        migrations.AddField(
            model_name="eventsettings",
            name="expert_linkedin",
            field=models.URLField(
                blank=True, default="https://www.linkedin.com/in/dhawalshrivastava/"
            ),
        ),
        migrations.AddField(
            model_name="eventsettings",
            name="faculty_coordinator_detail",
            field=models.CharField(default="Dept. of CSE", max_length=180),
        ),
        migrations.AddField(
            model_name="eventsettings",
            name="faculty_coordinator_email",
            field=models.EmailField(default="djain@piemr.edu.in", max_length=254),
        ),
        migrations.AddField(
            model_name="eventsettings",
            name="faculty_coordinator_name",
            field=models.CharField(default="Prof Dr. Dinesh C Jain", max_length=140),
        ),
        migrations.AddField(
            model_name="eventsettings",
            name="organized_by",
            field=models.CharField(
                default="Dept. of Computer Science Engineering & AIDS, PIEMR",
                max_length=220,
            ),
        ),
        migrations.AddField(
            model_name="eventsettings",
            name="student_coordinator_detail",
            field=models.CharField(default="4 Sem CSE, PIEMR", max_length=180),
        ),
        migrations.AddField(
            model_name="eventsettings",
            name="student_coordinator_email",
            field=models.EmailField(default="51110105688@piemr.edu.in", max_length=254),
        ),
        migrations.AddField(
            model_name="eventsettings",
            name="student_coordinator_name",
            field=models.CharField(default="Mr. Agastya Sharma", max_length=140),
        ),
        migrations.AddField(
            model_name="eventsettings",
            name="volunteer_details",
            field=models.TextField(
                blank=True,
                help_text="Add one volunteer per line. Example: Name | Role/Class | email@example.com",
            ),
        ),
        migrations.AlterField(
            model_name="eventsettings",
            name="expert_name",
            field=models.CharField(default="Mr. Dhawal Shrivastava", max_length=120),
        ),
    ]
