# Generated by Django 6.0.4 on 2026-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_eventsettings_expert_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsettings",
            name="developer_linkedin",
            field=models.URLField(
                blank=True,
                help_text="Agastya Sharma LinkedIn profile URL for the footer credit.",
            ),
        ),
    ]
