# Generated by Django 5.2.17 on 2026-09-27 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_eventsettings_developer_linkedin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsettings",
            name="organized_by",
            field=models.CharField(
                default="PIEMR Student Council & Cultural Committee", max_length=220
            ),
        ),
        migrations.AlterField(
            model_name="eventsettings",
            name="title",
            field=models.CharField(
                default="Urjotsav 2K26 - Annual Fest", max_length=220
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("resource", models.CharField(max_length=80)),
                ("resource_id", models.CharField(blank=True, max_length=80)),
                ("result", models.CharField(default="success", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cardiq_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=180)),
                ("job_title", models.CharField(blank=True, max_length=180)),
                (
                    "company",
                    models.CharField(blank=True, db_index=True, max_length=180),
                ),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=48)),
                ("website", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cardiq_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_code",
                    models.CharField(db_index=True, max_length=18, unique=True),
                ),
                ("original_name", models.CharField(blank=True, max_length=255)),
                (
                    "original_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="cardiq/originals/"
                    ),
                ),
                (
                    "processed_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="cardiq/processed/"
                    ),
                ),
                ("raw_text", models.TextField(blank=True)),
                ("structured_data", models.JSONField(blank=True, default=dict)),
                ("validation_result", models.JSONField(blank=True, default=dict)),
                ("qr_data", models.JSONField(blank=True, default=dict)),
                ("field_confidence", models.JSONField(blank=True, default=dict)),
                ("ocr_confidence", models.FloatField(default=0)),
                ("extraction_confidence", models.FloatField(default=0)),
                (
                    "duplicate_status",
                    models.CharField(default="No duplicate", max_length=32),
                ),
                ("processing_ms", models.PositiveIntegerField(default=0)),
                ("device", models.CharField(default="Desktop", max_length=80)),
                ("platform", models.CharField(default="Browser", max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("review", "Needs review"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="complete",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scans",
                        to="events.contact",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cardiq_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["user", "full_name"], name="events_cont_user_id_b39255_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(
                fields=["user", "created_at"], name="events_scan_user_id_2e8d1e_idx"
            ),
        ),
    ]
